{"status": "resolved", "priority": "urgent", "title": "Google Code bug importer crashes with AttributeError", "milestone": "0.11.01", "superceder": "", "nosylist": ["paulproteus, pythonian4000"], "assigned": "pythonian4000", "waitingon": "", "keywords": [], "id": "201", "files": [], "history": [{"message": "I'm not going to bother; I will be working on asyncification of the importer\nnext milestone (likely with your help ^_^) so all of the patches I have just\napplied will likely be defunct anyway =)\n   \n", "author": "pythonian4000"}, {"message": "It's going to be easier to test this post-asyncification.\n\nJack, if you don't want to bother writing a test, just mark this as resolved.\n   \n", "author": "paulproteus"}, {"message": "Fixed! Sorry for ganking this from you.\n\nIt was a really simple patch, but I tried for about half an hour to write a test\nfor it, and I couldn't quite write one. Can you, maybe, post-Jan 17?\n\nIf so, feel free to keep it assigned to you (we can rename it).\n\n<a href=\"http://gitorious.org/openhatch/oh-mainline/commit/c6b7a183572b368972a619b165092d3430300da1\">http://gitorious.org/openhatch/oh-mainline/commit/c6b7a183572b368972a619b165092d3430300da1</a>\nis the commit!\n   \n", "author": "paulproteus"}, {"message": "I might give this a shot, since it's blocking the nightly run bug tracker import.\n   \n", "author": "paulproteus"}, {"message": "I do maybe want to look into this :)\n\nI am away until the 17th of January, so will start this then.\n   \n", "author": "pythonian4000"}, {"message": "(jack, do you maybe want to look into this?)\n   \n", "author": "paulproteus"}, {"message": "A crash from the nightly bug crawl:\n\n2011-01-08 15:01:46,470 create_or_refresh_one_google_bug:220 INFO     [Google]\nRefreshing bug 1376 from project named SymPy.\nTraceback (most recent call last):\n  File \"./bin/production\", line 79, in &lt;module&gt;\n    djangorecipe.manage.main('mysite.deployment_settings')\n  File\n\"/home/deploy/milestone-a/eggs/djangorecipe-0.20-py2.6.egg/djangorecipe/manage.py\",\nline 16, in main\n    management.execute_manager(mod)\n  File\n\"/home/deploy/milestone-a/parts/production/django/core/management/__init__.py\",\nline 362, in execute_manager\n    utility.execute()\n  File\n\"/home/deploy/milestone-a/parts/production/django/core/management/__init__.py\",\nline 303, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File\n\"/home/deploy/milestone-a/parts/production/django/core/management/base.py\", line\n195, in run_from_argv\n    self.execute(*args, **options.__dict__)\n  File\n\"/home/deploy/milestone-a/parts/production/django/core/management/base.py\", line\n222, in execute\n    output = self.handle(*args, **options)\n  File\n\"/home/deploy/milestone-a/mysite/customs/management/commands/customs_daily_tasks.py\",\nline 176, in handle\n    self.find_and_update_enabled_google_instances()\n  File\n\"/home/deploy/milestone-a/mysite/customs/management/commands/customs_daily_tasks.py\",\nline 135, in find_and_update_enabled_google_tances\n    instantiated.update()\n  File \"/home/deploy/milestone-a/mysite/customs/bugtrackers/google.py\", line\n256, in update\n    self.create_or_refresh_one_google_bug(gb=gb)\n  File \"/home/deploy/milestone-a/mysite/customs/bugtrackers/google.py\", line\n223, in create_or_refresh_one_google_bug\n    data = gb.as_data_dict_for_bug_object(self.extract_tracker_specific_data)\n  File \"/home/deploy/milestone-a/mysite/customs/bugtrackers/google.py\", line\n151, in as_data_dict_for_bug_object\n    ret_dict = extract_tracker_specific_data(issue, ret_dict)\n  File \"/home/deploy/milestone-a/mysite/customs/bugtrackers/google.py\", line\n293, in extract_tracker_specific_data\n    ret_dict['bite_size_tag_name'] = gt.bitesized_label\nAttributeError: 'GoogleTracker' object has no attribute 'bitesized_label'\n   \n", "author": "paulproteus"}]}