{"status": "resolved", "priority": "urgent", "title": "Trac importer explodes when both \"Assigned:\" and \"Owner:\" fields are missing", "milestone": "0.11.01", "superceder": "", "nosylist": ["paulproteus, pythonian4000"], "assigned": "pythonian4000", "waitingon": "", "keywords": [], "id": "231", "files": [], "history": [{"message": "Hey Jack,\n\nI'm adding this for now, without a test. As we move forward into the beautiful\nasync future, I'm going to start insist on more tests.\n   \n", "author": "paulproteus"}, {"message": "While working on <a href=\"https://openhatch.org/bugs/issue97\">https://openhatch.org/bugs/issue97</a> I found that one of the\nTango bugs killed the importer. Turned out that bug didn't have \"Assigned:\" or\n\"Owner\" set, and the people-counter got upset. This patch fixes that.\n\n<a href=\"http://git.jackgrigg.com/openhatch/patch/?id=c70b4b6ed96a16d94fab42b9e499e2b3b81e1e4b\">http://git.jackgrigg.com/openhatch/patch/?id=c70b4b6ed96a16d94fab42b9e499e2b3b81e1e4b</a>\n   \n", "author": "pythonian4000"}]}