{"status": "resolved", "priority": "bug", "title": "Make migration infrastructure South 0.7-compatible", "milestone": "0.11.02", "superceder": "", "nosylist": ["jesstess, paulproteus"], "assigned": "", "waitingon": "", "keywords": [], "id": "308", "files": [{"url": "http://openhatch.org/bugs/file145/migration_errors_out.txt", "author": "jesstess"}], "history": [{"message": "<a href=\"http://south.aeracode.org/ticket/728\">http://south.aeracode.org/ticket/728</a> has a patch.\n\nI rolled it into a \"release\" of South that OpenHatch now depends on. Just\nre-pull, then re-run buildout.\n\nI'll mark this as \"resolved\". I'll also email Devel.\n   \n", "author": "paulproteus"}, {"message": "solution:\nln -s 0065_profile-now-has-bio.py  0065_profile_now_has_bio.py\ndrop db\ndrop user/privileges\nrecreate db with script and continue from that point on (following the README)\n   \n", "author": "zathras"}, {"message": "rerunning the migration after a rename seems not to fix things:\n\n\nRunning migrations for search:\n- Nothing to migrate.\nRunning migrations for profile:\n ! Migration profile:0068_add_homepage_url_models should not have been applied \nbefore profile:0065_profile_now_has_bio but was.\nTraceback (most recent call last):\n  File \"./bin/mysite\", line 74, in &lt;module&gt;\n    djangorecipe.manage.main('mysite.settings')\n  File \"/home/system/www2/openhatch.org/oh-mainline/eggs/djangorecipe-0.20-\npy2.6.egg/djangorecipe/manage.py\", line 16, in main\n    management.execute_manager(mod)\n  File \"/usr/lib/pymodules/python2.6/django/core/management/__init__.py\", line \n438, in execute_manager\n    utility.execute()\n  File \"/usr/lib/pymodules/python2.6/django/core/management/__init__.py\", line \n379, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File \"/usr/lib/pymodules/python2.6/django/core/management/base.py\", line 191, \nin run_from_argv\n    self.execute(*args, **options.__dict__)\n  File \"/usr/lib/pymodules/python2.6/django/core/management/base.py\", line 220, \nin execute\n    output = self.handle(*args, **options)\n  File \"/usr/lib/pymodules/python2.6/south/management/commands/migrate.py\", line \n102, in handle\n    delete_ghosts = delete_ghosts,\n  File \"/usr/lib/pymodules/python2.6/south/migration/__init__.py\", line 196, in \nmigrate_app\n    raise exceptions.InconsistentMigrationHistory(problems)\nsouth.exceptions.InconsistentMigrationHistory: Inconsistent migration history\nThe following options are available:\n    --merge: will just attempt the migration ignoring any potential dependency \nconflicts.\n   \n", "author": "zathras"}, {"message": "South 0.7 has slightly different and more strict migration file naming conventions than South 0.6, \nwhich was used to create many of our migration scripts. Right now, if you try to use South 0.7 to \ndo the OpenHatch database migration (ie \"./bin/mysite migrate\" as described in README.mkd), \nyou'll error out with:\n\n _mysql_exceptions.OperationalError: (1054, \"Unknown column 'profile_person.bio' in 'field list'\")\n\nThe issues is that \nmysite/profile/migrations/0069_fix_wrong_encoded_data_in_location_display_name.py cares about \nprofile_person.bio, but mysite/profile/migrations/0065_profile-now-has-bio.py, which adds the \nbio field, was skipped because it has an invalid migration script name under South 0.7. (see the \nattachment for more of the traceback)\n\nThe short-term solution for contributors who run into this problem on their local instance is to \nrename 0065_profile-now-has-bio.py to 0065_profile_now_has_bio.py and re-run the migration.\n   \n", "author": "jesstess"}]}