{"status": "resolved", "priority": "bug", "title": "Sometimes the profile editor fails to save, due to 'receive_maintainer_updates' being missing", "milestone": "0.11.03", "superceder": "", "nosylist": ["jesstess, paulproteus, pythonian4000"], "assigned": "paulproteus", "waitingon": "", "keywords": [], "id": "327", "files": [], "history": [{"message": "This was fixed when we fixed the ?x bug, <a href=\"issue255\">issue255</a>.\n   \n", "author": "paulproteus"}, {"message": "File\n\"/home/deploy/milestone-a.buildout/parts/production/django/core/handlers/base.py\",\nline 99, in get_response                                    \n    response = callback(request, *callback_args, **callback_kwargs)            \n                                                                      \n                                                                               \n                                                                      \n  File\n\"/home/deploy/milestone-a.buildout/parts/production/django/contrib/auth/decorators.py\",\nline 78, in __call__                                   \n    return self.view_func(request, *args, **kwargs)                            \n                                                                      \n                                                                               \n                                                                        File\n\"/home/deploy/milestone-a.buildout/mysite/profile/views.py\", line 1028, in\nsave_portfolio_entry_do                                             \n    request.POST['receive_maintainer_updates'].lower() not in ('false', '0')   \n                                                                      \n                                                                               \n                                                                      \n  File\n\"/home/deploy/milestone-a.buildout/parts/production/django/utils/datastructures.py\",\nline 238, in __getitem__                                  \n    raise MultiValueDictKeyError, \"Key %r not found in %r\" % (key, self)       \n                                                                      \n                                                                               \n                                                                     \nMultiValueDictKeyError: 'Key \\'receive_maintainer_updates\\' not found in\n&lt;QueryDict: {u\\'experience_description\\': [u\\'\\'], u\\'project_name\\':        \n[u\\'\\'], u\\'portfolio_entry__pk\\': [u\\'10315\\'], u\\'pf_entry_element_id\\':\n[u\\'portfolio_entry_10315\\'], u\\'project_description\\': [u\"This is an      \nextended version of the original Django MediaWiki Authentication extension that\nuses the Django User\\'s primary key as the linking information,       \nrather than the username (since it is possible for the username on either end to\nbe changed).\"]}&gt;'\n   \n", "author": "paulproteus"}]}