{"status": "resolved", "priority": "urgent", "title": "Migration 0021 from customs fails on live site", "milestone": "0.11.04", "superceder": "", "nosylist": ["paulproteus, pythonian4000"], "assigned": "pythonian4000", "waitingon": "", "keywords": [], "id": "376", "files": [], "history": [{"message": "This is deployed, although I added a patch on top that broke /customs/.\n\nOops-ish.\n   \n", "author": "paulproteus"}, {"message": "Fixed - I must have not changed the tracker fields on the BugzillaQueryModel and\nGoogleQueryModel models to point at the correct models when I created that data\nmigration.\n<a href=\"http://git.jackgrigg.com/openhatch/patch/?id=21ab35d838d704bc456774090bb6447d47960e54\">http://git.jackgrigg.com/openhatch/patch/?id=21ab35d838d704bc456774090bb6447d47960e54</a>\n   \n", "author": "pythonian4000"}, {"message": "It fails for me locally, too:\n\nError in migration: customs:0021_copy_tracker_model_data_across\nTraceback (most recent call last):\n  File \"./bin/production\", line 80, in &lt;module&gt;\n    djangorecipe.manage.main('mysite.deployment_settings')\n  File\n\"/home/deploy/milestone-a.buildout/eggs/djangorecipe-0.20-py2.6.egg/djangorecipe/manage.py\",\nline 16, in main\n    management.execute_manager(mod)\n  File\n\"/home/deploy/milestone-a.buildout/parts/production/django/core/management/__init__.py\",\nline 438, in execute_manager\n    utility.execute()\n  File\n\"/home/deploy/milestone-a.buildout/parts/production/django/core/management/__init__.py\",\nline 379, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File\n\"/home/deploy/milestone-a.buildout/parts/production/django/core/management/base.py\",\nline 191, in run_from_argv\n    self.execute(*args, **options.__dict__)\n  File\n\"/home/deploy/milestone-a.buildout/parts/production/django/core/management/base.py\",\nline 220, in execute\n    output = self.handle(*args, **options)\n  File\n\"/home/deploy/milestone-a.buildout/eggs/South-0.7.3.1-py2.6.egg/south/management/commands/migrate.py\",\nline 107, in handle\n    ignore_ghosts = ignore_ghosts,\n  File\n\"/home/deploy/milestone-a.buildout/eggs/South-0.7.3.1-py2.6.egg/south/migration/__init__.py\",\nline 191, in migrate_app\n    success = migrator.migrate_many(target, workplan, database)\n  File\n\"/home/deploy/milestone-a.buildout/eggs/South-0.7.3.1-py2.6.egg/south/migration/migrators.py\",\nline 222, in migrate_many\n    result = migrator.__class__.migrate_many(migrator, target, migrations, database)\n  File\n\"/home/deploy/milestone-a.buildout/eggs/South-0.7.3.1-py2.6.egg/south/migration/migrators.py\",\nline 293, in migrate_many\n    result = self.migrate(migration, database)\n  File\n\"/home/deploy/milestone-a.buildout/eggs/South-0.7.3.1-py2.6.egg/south/migration/migrators.py\",\nline 126, in migrate\n    result = self.run(migration)\n  File\n\"/home/deploy/milestone-a.buildout/eggs/South-0.7.3.1-py2.6.egg/south/migration/migrators.py\",\nline 100, in run\n    return self.run_migration(migration)\n  File\n\"/home/deploy/milestone-a.buildout/eggs/South-0.7.3.1-py2.6.egg/south/migration/migrators.py\",\nline 81, in run_migration\n    migration_function()\n  File\n\"/home/deploy/milestone-a.buildout/eggs/South-0.7.3.1-py2.6.egg/south/migration/migrators.py\",\nline 57, in &lt;lambda&gt;\n    return (lambda: direction(orm))\n  File\n\"/home/deploy/milestone-a.buildout/mysite/customs/migrations/0021_copy_tracker_model_data_across.py\",\nline 59, in forwards\n    tracker = gtm,\n  File\n\"/home/deploy/milestone-a.buildout/parts/production/django/db/models/manager.py\", line\n138, in create\n    return self.get_query_set().create(**kwargs)\n  File\n\"/home/deploy/milestone-a.buildout/parts/production/django/db/models/query.py\",\nline 356, in create\n    obj = self.model(**kwargs)\n  File\n\"/home/deploy/milestone-a.buildout/parts/production/django/db/models/base.py\",\nline 350, in __init__\n    setattr(self, field.name, rel_obj)\n  File\n\"/home/deploy/milestone-a.buildout/parts/production/django/db/models/fields/related.py\",\nline 329, in __set__\n    self.field.name, self.field.rel.to._meta.object_name))\nValueError: Cannot assign \"&lt;GoogleTrackerModel: GoogleTrackerModel object&gt;\":\n\"GoogleQueryModel.tracker\" must be a \"GoogleTracker\" instance.\n   \n", "author": "paulproteus"}]}