{"status": "resolved", "priority": "critical", "title": "The \"Debian GNU/Linux\" project page (map) has zero people on it", "milestone": "0.11.11", "superceder": "", "nosylist": ["paulproteus"], "assigned": "paulproteus", "waitingon": "", "keywords": [], "id": "538", "files": [], "history": [{"message": "* The map backend is now fixed, through no longer using Haystack (see <a href=\"issue89\">issue89</a> )\n\n* The \"/+projects/Debian GNU/Linux\" page now no longer uses\ncached_contributor_count, which was set to an old, incorrect value (47 vs. 46)\n\nThis should close the issue solidly.\n   \n", "author": "paulproteus"}, {"message": "Progress on this bug:\n\n* <a href=\"https://openhatch.org/people/?q=project:%22Debian%20GNU/Linux%22\">https://openhatch.org/people/?q=project:%22Debian%20GNU/Linux%22</a> now shows 46\ncontributors (and more-over uses the ORM, not Haystack, for searching)\n\n* <a href=\"http://openhatch.org/+projects/Debian%20GNU/Linux\">http://openhatch.org/+projects/Debian%20GNU/Linux</a> says 47 contributors, but\nthe map page says 46 . So \"nearly there\"\n\n* This is probably a bug with cached_contributor_count on the Project object .\nMaybe we can get away with just removing that entirely from the database.\n   \n", "author": "paulproteus"}, {"message": "I'll take this for myself, and also into 0.11.11.\n\nWhen we run 'python manage.py rebuild_index' on the deployment, we get told:\n\nhaystack.exceptions.SearchBackendError: No fields were found in any\nsearch_indexes. Please correct this before attempting to search.\n\nThat is bad news -- it means that there is no way our Haystack+Xapian-based\nsearch (on e.g. /people/) can work.\n   \n", "author": "paulproteus"}, {"message": "There is a problem with the way are querying Haystack, and the result is that\n<a href=\"https://openhatch.org/people/?q=project:%22Debian%20GNU/Linux%22\">https://openhatch.org/people/?q=project:%22Debian%20GNU/Linux%22</a> is empty, even\nthough that's rather false.\n   \n", "author": "paulproteus"}]}