{"status": "resolved", "priority": "bug", "title": "When running Profile test in non-production system I get the error \".postmap: fatal: open /etc/postfix/virtual_alias_maps: No such file or directory\". The tests need to be skipped.", "milestone": "", "superceder": "", "nosylist": ["paulproteus, sunu"], "assigned": "", "waitingon": "", "keywords": ["bitesize"], "id": "850", "files": [], "history": [{"message": "Closed in <a href=\"https://github.com/sunu/oh-\">https://github.com/sunu/oh-</a>\nmainline/commit/1b21f720415cc8f0fa49c03703c1d5e39b154484 which includes \n<a href=\"https://github.com/sunu/oh-\">https://github.com/sunu/oh-</a>\nmainline/commit/cfd442e3d0dcb04a68e56d968289f9feb411c851 .\n\nThanks sunu!\n   \n", "author": "paulproteus"}, {"message": "More info:\n\nIf you run 'python manage.py test profile' you'll see lots of what I call \"spew\" \nrelated to this postmap command trying to be run.\nThe right fix here is to take a look at settings.py and notice a few things:\n\n(1) POSTFIX_FORWARDER_TABLE_PATH = None is set by default\n\n(2) In mysite/deployment_settings.py there's an override for production time\n\nSo the question is -- why do we even bother running the postmap command when POSTFIX_FORWARDER_TABLE_PATH is set to None?\n\nThe answer is, We shouldn't; it's a bug.\n\nThat's the bug! You'll also have to add tests to this that cover both cases, and \nthat part might get tricky, but you might be able to find inspiration from the \nexisting tests of that part of the code.\n\nIf you get stuck on the testing part, feel very free to request help!\n   \n", "author": "paulproteus"}]}